### ISSUE TITLE
Headers - correct distance between subsequent sections

### ISSUE THREAD

**Issue by KamilBarczyk** [smootny/gaweloft#13]

**Comment by KamilBarczyk** [comment]
@smootny Could you assign me to this task? I probably don't have the appropriate permissions to do this 😬

**Comment by smootny** [comment]
sure!

**Comment by KamilBarczyk** [comment]
I confirm that the visibility on the connected monitor is correct. 
I would consider a different distance between sections and headers. They should all look like by the word "Realizacja".
<img width="1124" alt="Realizacja" src="https://github.com/smootny/gaweloft/assets/62600472/1b43788e-aa6e-43b9-a83a-19f7e5a16c15">
<img width="1128" alt="Oferta" src="https://github.com/smootny/gaweloft/assets/62600472/c7a6fe50-4f57-4b7a-b1f9-bf64f8eee034">


But we need to fix the correct display on the laptop !
